export function spatialInspectorHtml(
  nonce: string,
  options: { readonly backHref?: string; readonly backLabel?: string } = {}
): string {
  const backHref = options.backHref ?? '/inspector'
  const backLabel = options.backLabel ?? 'Back to Inspector'
  return String.raw`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
  <title>Boron Spatial Inspector</title>
  <style nonce="${nonce}">
    :root { color-scheme:dark; --bg:#020809; --panel:#061315e8; --line:#1f5960; --text:#efffff; --muted:#8eb0b4; --acid:#a8ff4f; --cyan:#36e6ff; --purple:#bd7dff; --warn:#ffc764; }
    * { box-sizing:border-box; }
    html,body { margin:0; width:100%; height:100%; overflow:hidden; background:radial-gradient(circle at 54% 44%,#0c3033 0,#031012 36%,#020607 74%); color:var(--text); font:14px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
    body:after { content:""; position:fixed; inset:0; pointer-events:none; background:linear-gradient(#36e6ff08 1px,transparent 1px),linear-gradient(90deg,#36e6ff08 1px,transparent 1px); background-size:44px 44px; mask-image:linear-gradient(to bottom,#0008,transparent 75%); }
    body:before { content:""; position:fixed; z-index:1; top:0; left:0; width:100%; height:2px; pointer-events:none; opacity:.38; background:linear-gradient(90deg,transparent,#36e6ff 48%,#a8ff4f 52%,transparent); box-shadow:0 0 14px #36e6ff88; animation:scan 8s linear infinite; }
    @keyframes scan { from { transform:translateY(-5vh); } to { transform:translateY(110vh); } }
    #xrCanvas { position:fixed; z-index:0; inset:0; width:100%; height:100%; touch-action:none; }
    #overlay { position:fixed; z-index:2; inset:0; pointer-events:none; }
    .panel { pointer-events:auto; position:absolute; top:18px; left:18px; width:min(410px,calc(100vw - 36px)); padding:16px; border:1px solid #36e6ff45; border-radius:16px; background:var(--panel); backdrop-filter:blur(18px); box-shadow:0 0 40px #1fe8ff10,0 18px 60px #0009; }
    .brand { display:flex; align-items:center; gap:11px; margin-bottom:13px; }
    .mark { width:34px; height:34px; display:grid; place-items:center; border:1px solid #baff78; border-radius:50%; background:#a8ff4f18; color:var(--acid); box-shadow:inset 0 0 18px #a8ff4f33,0 0 24px #a8ff4f22; font-weight:900; }
    h1,p { margin:0; }
    h1 { font-size:16px; letter-spacing:.11em; }
    .muted { color:var(--muted); font-size:12px; }
    .breadcrumbs { display:flex; align-items:center; gap:6px; min-height:30px; margin-top:11px; overflow:hidden; }
    .crumb { min-width:0; max-width:145px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; border:0; padding:3px 6px; color:var(--cyan); background:transparent; }
    .crumb:disabled { opacity:1; color:var(--text); }
    .separator { color:#48777b; }
    .controls { display:grid; grid-template-columns:1fr 1fr; gap:8px; margin-top:10px; }
    button,select,a.button { min-height:40px; border:1px solid #315b60; border-radius:10px; background:#0a2023; color:var(--text); padding:8px 10px; font:inherit; text-decoration:none; cursor:pointer; }
    button:hover,select:hover,a.button:hover { border-color:#36e6ff99; box-shadow:inset 0 0 16px #36e6ff0c; }
    button.primary { background:var(--acid); color:#07110b; border-color:var(--acid); font-weight:800; }
    button:disabled { opacity:.45; cursor:not-allowed; }
    select { width:100%; }
    .wide { grid-column:1/-1; }
    .stats { display:flex; flex-wrap:wrap; gap:7px; margin-top:12px; }
    .badge { border:1px solid #28565b; border-radius:999px; padding:4px 8px; color:var(--muted); background:#071719aa; font-size:11px; }
    .legend { position:absolute; left:18px; bottom:18px; display:flex; flex-wrap:wrap; gap:8px 13px; max-width:calc(100vw - 36px); padding:9px 11px; border:1px solid #28565b; border-radius:12px; background:var(--panel); color:var(--muted); font-size:11px; }
    .dot { display:inline-block; width:8px; height:8px; border-radius:50%; margin-right:5px; box-shadow:0 0 8px currentColor; }
    .detail { pointer-events:none; position:absolute; top:18px; right:18px; width:min(330px,calc(100vw - 36px)); padding:14px; border:1px solid #36e6ff55; border-radius:14px; background:var(--panel); opacity:0; transform:translateY(-8px); transition:.18s; box-shadow:0 0 34px #36e6ff12; }
    .detail.show { opacity:1; transform:none; }
    .detail strong { display:block; margin-bottom:5px; color:#d9fbff; }
    @media (max-width:820px) { .detail { top:auto; bottom:78px; } .legend { right:18px; } }
  </style>
</head>
<body>
  <canvas id="xrCanvas"></canvas>
  <div id="overlay">
    <section class="panel">
      <div class="brand"><div class="mark">B</div><div><h1>BORON SPATIAL WORKBENCH</h1><p class="muted">Progressive, read-only project intelligence</p></div></div>
      <p id="status" class="muted">Authenticating with the local Boron daemon…</p>
      <div id="breadcrumbs" class="breadcrumbs"></div>
      <div class="controls">
        <select id="project" class="wide" aria-label="Project"></select>
        <select id="layer" aria-label="Visible graph layer"><option value="combined">Ontology + code</option><option value="ontology">Ontology only</option><option value="codebase">Codebase only</option></select>
        <select id="effects" aria-label="Visual effects"><option value="cinematic">Cinematic FX</option><option value="balanced">Quest performance</option></select>
        <button id="backLevel" disabled>Back one level</button>
        <button id="refresh">Refresh</button>
        <button id="enterMR" class="primary wide" disabled>Enter Quest passthrough</button>
        <button id="exitMR" class="wide" hidden>Exit mixed reality</button>
        <a class="button wide" href="${backHref}">${backLabel}</a>
      </div>
      <div id="stats" class="stats"></div>
    </section>
    <aside id="detail" class="detail"><strong id="detailName"></strong><span id="detailMeta" class="muted"></span></aside>
    <div class="legend">
      <span><i class="dot" style="color:#a8ff4f;background:#a8ff4f"></i>confirmed ontology</span>
      <span><i class="dot" style="color:#ffc764;background:#ffc764"></i>candidate / review</span>
      <span><i class="dot" style="color:#36e6ff;background:#36e6ff"></i>live code-derived</span>
      <span>Pinch / trigger: drill down · two-hand pinch: scale + rotate</span>
    </div>
  </div>
  <script type="module" nonce="${nonce}">
    import * as THREE from '/inspector/assets/three.module.js';

    var canvas=document.getElementById('xrCanvas');
    var renderer=new THREE.WebGLRenderer({canvas:canvas,alpha:true,antialias:true,powerPreference:'high-performance'});
    renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.setSize(window.innerWidth,window.innerHeight);renderer.setClearColor(0x020809,1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local-floor');

    var scene=new THREE.Scene();var camera=new THREE.PerspectiveCamera(55,window.innerWidth/window.innerHeight,.02,40);camera.position.set(0,.08,3.65);
    scene.add(new THREE.HemisphereLight(0x9ffcff,0x06110d,1.7));var key=new THREE.PointLight(0x42e9ff,16,9);key.position.set(1.8,2.4,2.5);scene.add(key);var acidLight=new THREE.PointLight(0xa8ff4f,8,7);acidLight.position.set(-2,-1,1);scene.add(acidLight);
    var graphGroup=new THREE.Group();scene.add(graphGroup);var atmosphere=createAtmosphere();scene.add(atmosphere);
    var nodeMeshes=[];var edgeFlows=[];var shockwaves=[];var graphRevealAt=0;var currentOntology=null;var currentCodebase=null;var currentExpansion=null;var currentSession=null;var currentLod=0;var focusClusterId=null;var focusSymbolId=null;var selectedMesh=null;var hoverMesh=null;var expansionCache=new Map();
    var selectionHalo=new THREE.Mesh(new THREE.TorusGeometry(.095,.006,12,64),new THREE.MeshBasicMaterial({color:0xa8ff4f,transparent:true,opacity:.95,depthTest:false,blending:THREE.AdditiveBlending}));selectionHalo.visible=false;selectionHalo.renderOrder=30;scene.add(selectionHalo);
    var raycaster=new THREE.Raycaster();var rotationMatrix=new THREE.Matrix4();var lastFrameTime=0;var perfWindowStart=0;var perfFrames=0;var controllers=[];var gestures=[{active:false},{active:false}];var dualGesture=null;var gestureBlockedUntil=0;

    function api(path,body){return fetch(path,{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify(body||{})}).then(async function(response){var data=await response.json();if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data;});}
    function setStatus(message){document.getElementById('status').textContent=message;}
    function compactPath(value){var text=String(value||'');try{if(text.indexOf('file://')===0)text=decodeURIComponent(new URL(text).pathname);}catch(error){}return text.replace(/^\/Users\/[^/]+/,'~').replace(/^\/home\/[^/]+/,'~');}
    function indexedCodebaseProject(graph){var nodes=new Map(graph.nodes.map(function(node){return [node.id,node];}));var edge=graph.edges.find(function(item){var target=nodes.get(item.target);return item.relationType==='INDEXED_AS'&&item.confirmationState==='confirmed'&&target&&target.canonicalUri&&target.canonicalUri.indexOf('codebase-memory://')===0;});if(!edge)return null;return decodeURIComponent(nodes.get(edge.target).canonicalUri.slice('codebase-memory://'.length));}

    async function authenticate(){var ticket=new URLSearchParams(location.hash.slice(1)).get('ticket');history.replaceState(null,'',location.pathname);if(ticket)await api('/v1/inspector/session',{ticket:ticket});await loadProject('Boron Context');var arSupported=!!navigator.xr&&await navigator.xr.isSessionSupported('immersive-ar').catch(function(){return false;});document.getElementById('enterMR').disabled=!arSupported;if(arSupported)setStatus('Connected. Quest passthrough and standard XR input are ready.');else setStatus('3D workbench ready. Open the paired URL in Meta Quest Browser for passthrough.');}
    async function loadProject(projectHint){setStatus('Loading sourced graph data…');currentOntology=await api('/v1/inspector/ontology',{projectHint:projectHint});var codeProject=indexedCodebaseProject(currentOntology);currentCodebase=null;currentExpansion=null;expansionCache.clear();currentLod=0;focusClusterId=null;focusSymbolId=null;if(codeProject){try{currentCodebase=await api('/v1/inspector/codebase-spatial',{project:codeProject});}catch(error){setStatus('Ontology loaded; live code projection is unavailable.');}}renderProjects(currentOntology);rebuildGraph();setStatus('Overview loaded. Pinch a cyan architecture cluster to open it.');}
    function renderProjects(graph){var select=document.getElementById('project');var current=graph.project&&graph.project.id;select.innerHTML='';graph.projects.forEach(function(project){var option=document.createElement('option');option.value=project.sourceUri;option.textContent=project.name+' · '+compactPath(project.sourceUri);option.selected=project.id===current;select.appendChild(option);});}

    function codeNode(id){return currentCodebase&&currentCodebase.nodes.find(function(node){return node.id===id;});}
    function codeVisible(){if(!currentCodebase)return {nodes:[],edges:[]};var root=currentCodebase.nodes.find(function(node){return node.kind==='code_root';});if(currentLod===0){var overview=currentCodebase.nodes.filter(function(node){return node.kind==='code_root'||node.kind==='code_cluster';});var ids0=new Set(overview.map(function(node){return node.id;}));return {nodes:overview,edges:currentCodebase.edges.filter(function(edge){return ids0.has(edge.source)&&ids0.has(edge.target);})};}if(currentLod===1){var middle=currentCodebase.nodes.filter(function(node){return node.id===focusClusterId||node.parentId===focusClusterId||node.kind==='code_root';});var ids1=new Set(middle.map(function(node){return node.id;}));return {nodes:middle,edges:currentCodebase.edges.filter(function(edge){return ids1.has(edge.source)&&ids1.has(edge.target);})};}var base=[root,codeNode(focusClusterId),codeNode(focusSymbolId)].filter(Boolean);var merged=new Map(base.map(function(node){return [node.id,node];}));if(currentExpansion)currentExpansion.nodes.forEach(function(node){merged.set(node.id,node);});var ids2=new Set(merged.keys());var baseEdges=currentCodebase.edges.filter(function(edge){return ids2.has(edge.source)&&ids2.has(edge.target);});var expanded=currentExpansion?currentExpansion.edges.filter(function(edge){return ids2.has(edge.source)&&ids2.has(edge.target);}):[];return {nodes:Array.from(merged.values()),edges:baseEdges.concat(expanded)};}
    function ontologyVisible(layer){if(!currentOntology||layer==='codebase')return {nodes:[],edges:[]};var nodes=currentOntology.nodes.slice().sort(function(a,b){if(a.confirmationState!==b.confirmationState)return a.confirmationState==='candidate'?-1:1;return a.name.localeCompare(b.name);});if(layer==='combined'){nodes=nodes.filter(function(node){var kind=String(node.kind||'').toLowerCase();return node.confirmationState==='candidate'||kind.indexOf('project')>=0||kind.indexOf('capability')>=0||kind.indexOf('product')>=0;}).slice(0,currentLod===0?32:14);}else nodes=nodes.slice(0,160);var ids=new Set(nodes.map(function(node){return node.id;}));return {nodes:nodes,edges:currentOntology.edges.filter(function(edge){return ids.has(edge.source)&&ids.has(edge.target);}).slice(0,260)};}
    function visibleData(){var layer=document.getElementById('layer').value;var ontology=ontologyVisible(layer);var code=layer==='ontology'?{nodes:[],edges:[]}:codeVisible();return {nodes:ontology.nodes.map(function(node){return Object.assign({},node,{sourceLayer:'ontology'});}).concat(code.nodes.map(function(node){return Object.assign({},node,{sourceLayer:'codebase'});})),edges:ontology.edges.map(function(edge){return Object.assign({},edge,{sourceLayer:'ontology'});}).concat(code.edges.map(function(edge){return Object.assign({},edge,{sourceLayer:'codebase'});})),ontologyCount:ontology.nodes.length,codeCount:code.nodes.length};}

    function cinematic(){return document.getElementById('effects').value==='cinematic';}
    function rebuildGraph(){while(graphGroup.children.length){var child=graphGroup.children.pop();disposeObject(child);}nodeMeshes=[];edgeFlows=[];shockwaves=[];selectedMesh=null;hoverMesh=null;selectionHalo.visible=false;graphRevealAt=performance.now();document.getElementById('detail').classList.remove('show');var data=visibleData();var positions=new Map();layoutCode(data.nodes.filter(function(node){return node.sourceLayer==='codebase';}),positions);layoutOntology(data.nodes.filter(function(node){return node.sourceLayer==='ontology';}),positions);data.nodes.forEach(function(node,index){var mesh=createNode(node,positions.get(node.id),index);graphGroup.add(mesh);nodeMeshes.push(mesh);if(shouldLabel(node,index))graphGroup.add(labelSprite(node.name,mesh.position,nodeColor(node),index));if(node.kind==='code_root')decorateCore(mesh.position);});addEdges(data.edges,positions,'confirmed',0x78a9a5,.24);addEdges(data.edges,positions,'candidate',0xffc764,.72);addEdges(data.edges,positions,'derived',0x36e6ff,.58);addOrbitGuides(data.nodes);renderBreadcrumbs();var levelLabel=currentLod===0?'L0 architecture':currentLod===1?'L1 symbols':'L2 call graph';document.getElementById('stats').innerHTML='<span class="badge">'+levelLabel+'</span><span class="badge">'+data.ontologyCount+' ontology</span><span class="badge">'+data.codeCount+' code</span><span class="badge">'+data.edges.length+' visible links</span><span class="badge">FX '+(cinematic()?'cinematic':'balanced')+'</span><span id="perfBadge" class="badge">measuring FPS…</span><span class="badge">0 camera frames captured</span>';}
    function layoutCode(nodes,positions){var root=nodes.find(function(node){return node.kind==='code_root';});if(root)positions.set(root.id,currentLod===0?new THREE.Vector3(.48,0,0):new THREE.Vector3(-.9,.68,-.28));if(currentLod===0){var clusters=nodes.filter(function(node){return node.kind==='code_cluster';});clusters.forEach(function(node,index){var ring=index%2;var theta=(index/clusters.length)*Math.PI*2+ring*.23;var radius=ring?1.16:.84;positions.set(node.id,new THREE.Vector3(.48+Math.cos(theta)*radius,(ring?.31:-.2)+Math.sin(theta*2)*.2,Math.sin(theta)*radius*.62));});return;}if(currentLod===1){var cluster=nodes.find(function(node){return node.id===focusClusterId;});if(cluster)positions.set(cluster.id,new THREE.Vector3(.34,0,0));var symbols=nodes.filter(function(node){return node.kind==='code_symbol';});symbols.forEach(function(node,index){var theta=(index/Math.max(1,symbols.length))*Math.PI*2;positions.set(node.id,new THREE.Vector3(.34+Math.cos(theta)*.86,Math.sin(theta)*.58,Math.sin(theta*1.5)*.38));});return;}var cluster2=nodes.find(function(node){return node.id===focusClusterId;});if(cluster2)positions.set(cluster2.id,new THREE.Vector3(-.5,.55,-.08));var focus=nodes.find(function(node){return node.id===focusSymbolId;});if(focus)positions.set(focus.id,new THREE.Vector3(.38,0,0));var neighbors=nodes.filter(function(node){return node.kind==='code_symbol'&&node.id!==focusSymbolId;});neighbors.forEach(function(node,index){var ring2=index%2;var theta2=(index/Math.max(1,neighbors.length))*Math.PI*2;var radius2=ring2?1.02:.74;positions.set(node.id,new THREE.Vector3(.38+Math.cos(theta2)*radius2,Math.sin(theta2)*.67,Math.sin(theta2*1.35)*.46));});}
    function layoutOntology(nodes,positions){if(!nodes.length)return;var layer=document.getElementById('layer').value;var center=layer==='ontology'?.25:-1.36;var total=Math.max(1,nodes.length);nodes.forEach(function(node,index){var y=1-(index/Math.max(1,total-1))*2;var radius=Math.sqrt(Math.max(0,1-y*y));var theta=index*2.399963229728653;positions.set(node.id,new THREE.Vector3(center+Math.cos(theta)*radius*.5,y*.64,Math.sin(theta)*radius*.48-.25));});}

    function hologramMaterial(color,opacity){return new THREE.ShaderMaterial({uniforms:{holoColor:{value:new THREE.Color(color)},holoOpacity:{value:opacity}},vertexShader:'varying vec3 vNormal;varying vec3 vView;void main(){vec4 mv=modelViewMatrix*vec4(position,1.0);vNormal=normalize(normalMatrix*normal);vView=normalize(-mv.xyz);gl_Position=projectionMatrix*mv;}',fragmentShader:'uniform vec3 holoColor;uniform float holoOpacity;varying vec3 vNormal;varying vec3 vView;void main(){float rim=pow(1.0-abs(dot(vNormal,vView)),2.2);float scan=.72+.28*sin(gl_FragCoord.y*.16);gl_FragColor=vec4(holoColor,rim*holoOpacity*scan);}',transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide});}
    function createNode(node,position,index){var color=nodeColor(node);var candidate=node.confirmationState==='candidate';var geometry=node.kind==='code_root'?new THREE.IcosahedronGeometry(1,3):node.kind==='code_cluster'?new THREE.OctahedronGeometry(1,1):new THREE.IcosahedronGeometry(1,1);var material=candidate?new THREE.MeshBasicMaterial({color:color,wireframe:true,transparent:true,opacity:.9}):new THREE.MeshStandardMaterial({color:color,emissive:color,emissiveIntensity:node.sourceLayer==='codebase'?.5:.24,roughness:.16,metalness:.72,transparent:true,opacity:node.kind==='code_root'?.96:.9});var mesh=new THREE.Mesh(geometry,material);var size=node.kind==='code_root'?.16:node.kind==='code_cluster'?Math.min(.11,.066+Math.log2(Math.max(2,node.weight||2))*.009):(candidate?.058:.052);mesh.scale.setScalar(.001);mesh.position.copy(position||new THREE.Vector3());mesh.userData.graphNode=node;mesh.userData.baseScale=size;mesh.userData.visualMultiplier=1;mesh.userData.revealDelay=index*.035;mesh.userData.pulse=Math.random()*Math.PI*2;mesh.renderOrder=5;var aura=new THREE.Mesh(geometry.clone(),hologramMaterial(color,node.kind==='code_root'?.9:.58));aura.scale.setScalar(1.72);mesh.add(aura);if(node.sourceLayer==='codebase'){var cage=new THREE.Mesh(geometry.clone(),new THREE.MeshBasicMaterial({color:color,wireframe:true,transparent:true,opacity:.3,depthWrite:false,blending:THREE.AdditiveBlending}));cage.scale.setScalar(.82);mesh.add(cage);}return mesh;}
    function decorateCore(position){var glow=glowSprite(0xa8ff4f,.78,.18);glow.position.copy(position);graphGroup.add(glow);[0,.9,1.8,2.7].forEach(function(offset,index){var ring=new THREE.Mesh(new THREE.TorusGeometry(.23+index*.047,.0035,8,96),new THREE.MeshBasicMaterial({color:index===1||index===3?0xa8ff4f:0x36e6ff,transparent:true,opacity:.62-index*.07,depthWrite:false,blending:THREE.AdditiveBlending}));ring.position.copy(position);ring.rotation.set(offset*.31,offset,offset*.2);ring.userData.spin=.0032*(index%2?-1:1);graphGroup.add(ring);});var beam=new THREE.Mesh(new THREE.CylinderGeometry(.006,.018,.82,12,1,true),new THREE.MeshBasicMaterial({color:0x36e6ff,transparent:true,opacity:.11,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}));beam.position.copy(position);graphGroup.add(beam);for(var i=0;i<(cinematic()?5:3);i++){var electron=new THREE.Mesh(new THREE.SphereGeometry(.012,8,6),new THREE.MeshBasicMaterial({color:i%2?0xa8ff4f:0x8ff7ff,depthWrite:false,blending:THREE.AdditiveBlending}));electron.userData.orbit={center:position.clone(),radius:.29+i*.045,speed:.45+i*.09,phase:i*1.256,tilt:(i-2)*.35};graphGroup.add(electron);}}
    function addOrbitGuides(nodes){if(!nodes.some(function(node){return node.kind==='code_root';}))return;for(var i=0;i<2;i++){var guide=new THREE.Mesh(new THREE.TorusGeometry((currentLod===0?1.07:.81)+i*.11,.0022,6,144),new THREE.MeshBasicMaterial({color:i?0xa8ff4f:0x36e6ff,transparent:true,opacity:i?.07:.14,depthWrite:false,blending:THREE.AdditiveBlending}));guide.rotation.set(Math.PI/(2.55+i*.3),i*.22,0);guide.position.set(currentLod===0?.48:.34,0,0);guide.userData.spin=.00045*(i?-1:1);graphGroup.add(guide);}}
    function radialTexture(color){var surface=document.createElement('canvas');surface.width=128;surface.height=128;var context=surface.getContext('2d');var gradient=context.createRadialGradient(64,64,0,64,64,64);gradient.addColorStop(0,'rgba(255,255,255,.95)');gradient.addColorStop(.12,'#'+new THREE.Color(color).getHexString());gradient.addColorStop(.42,'rgba(40,235,255,.18)');gradient.addColorStop(1,'rgba(0,0,0,0)');context.fillStyle=gradient;context.fillRect(0,0,128,128);var texture=new THREE.CanvasTexture(surface);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
    function glowSprite(color,size,opacity){var texture=radialTexture(color);var sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,color:color,transparent:true,opacity:opacity,depthWrite:false,blending:THREE.AdditiveBlending}));sprite.scale.set(size,size,1);sprite.userData.ownedTexture=texture;return sprite;}
    function createAtmosphere(){var group=new THREE.Group();var count=cinematic()?280:170;var values=new Float32Array(count*3);var colors=new Float32Array(count*3);for(var i=0;i<count;i++){values[i*3]=(Math.random()-.5)*7;values[i*3+1]=(Math.random()-.5)*4.5;values[i*3+2]=(Math.random()-.5)*5;colors[i*3]=.2+Math.random()*.25;colors[i*3+1]=.72+Math.random()*.28;colors[i*3+2]=.85+Math.random()*.15;}var geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(values,3));geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));var points=new THREE.Points(geometry,new THREE.PointsMaterial({size:.014,vertexColors:true,transparent:true,opacity:.42,depthWrite:false,blending:THREE.AdditiveBlending}));group.add(points);var grid=new THREE.GridHelper(8,40,0x1de2ef,0x0b454a);grid.position.y=-1.05;grid.material.transparent=true;grid.material.opacity=.15;group.add(grid);var cloud=glowSprite(0x36e6ff,3.8,.04);cloud.position.set(1,.2,-1.5);group.add(cloud);return group;}
    function nodeColor(node){if(node.confirmationState==='candidate')return 0xffc764;if(node.sourceLayer==='codebase')return node.kind==='code_root'?0xa8ff4f:node.kind==='code_cluster'?0x36e6ff:0xbd7dff;var kind=String(node.kind||'').toLowerCase();if(kind.indexOf('project')>=0)return 0xa8ff4f;if(kind.indexOf('capability')>=0)return 0x36e6ff;if(kind.indexOf('artifact')>=0)return 0xbd7dff;return 0xd9fbff;}
    function shouldLabel(node,index){var kind=String(node.kind||'').toLowerCase();return index<32||node.confirmationState==='candidate'||kind.indexOf('project')>=0||kind==='code_root'||kind==='code_cluster';}
    function labelSprite(text,position,color,index){var label=String(text||'').slice(0,38);var surface=document.createElement('canvas');surface.width=512;surface.height=96;var context=surface.getContext('2d');context.clearRect(0,0,512,96);context.fillStyle='rgba(1,11,14,.78)';context.roundRect(2,8,508,80,18);context.fill();context.strokeStyle='#'+new THREE.Color(color).getHexString();context.lineWidth=3;context.stroke();context.fillStyle='#efffff';context.font='700 27px -apple-system, BlinkMacSystemFont, sans-serif';context.textBaseline='middle';context.fillText(label,20,49,470);var texture=new THREE.CanvasTexture(surface);texture.colorSpace=THREE.SRGBColorSpace;var material=new THREE.SpriteMaterial({map:texture,transparent:true,opacity:0,depthWrite:false});var sprite=new THREE.Sprite(material);sprite.position.copy(position).add(new THREE.Vector3(.19,.068,0));sprite.scale.set(.5,.094,1);sprite.userData.labelTexture=texture;sprite.userData.revealDelay=index*.035+.13;return sprite;}
    function addEdges(edges,positions,state,color,opacity){var selected=edges.filter(function(edge){return edge.confirmationState===state;});selected.forEach(function(edge,index){var a=positions.get(edge.source),b=positions.get(edge.target);if(!a||!b)return;var edgeColor=edge.relationType==='CALLS'?0xbd7dff:color;var midpoint=a.clone().add(b).multiplyScalar(.5);var distance=a.distanceTo(b);var sign=index%2?-1:1;var control=midpoint.clone().add(new THREE.Vector3(0,sign*(.055+distance*.035),sign*(.11+distance*.07)));var curve=new THREE.QuadraticBezierCurve3(a.clone(),control,b.clone());var geometry=new THREE.BufferGeometry().setFromPoints(curve.getPoints(cinematic()?34:22));var line=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:edgeColor,transparent:true,opacity:opacity,depthWrite:false,blending:THREE.AdditiveBlending}));line.userData.pulseLine=true;line.userData.baseOpacity=opacity;graphGroup.add(line);if(state==='derived'&&cinematic()){var tube=new THREE.Mesh(new THREE.TubeGeometry(curve,20,.0035,5,false),new THREE.MeshBasicMaterial({color:edgeColor,transparent:true,opacity:.14,depthWrite:false,blending:THREE.AdditiveBlending}));graphGroup.add(tube);}if(state==='derived'){var count=cinematic()?2:1;for(var particleIndex=0;particleIndex<count&&edgeFlows.length<(cinematic()?36:18);particleIndex++){var particle=new THREE.Mesh(new THREE.SphereGeometry(cinematic()?.009:.008,7,5),new THREE.MeshBasicMaterial({color:edgeColor,transparent:true,opacity:.96,depthWrite:false,blending:THREE.AdditiveBlending}));particle.userData.flow={curve:curve,progress:(index*.173+particleIndex*.48)%1,speed:.2+(index%5)*.018};particle.position.copy(curve.getPoint(particle.userData.flow.progress));graphGroup.add(particle);edgeFlows.push(particle);}}});}
    function disposeObject(object){object.traverse(function(child){if(child.geometry)child.geometry.dispose();if(child.material){var materials=Array.isArray(child.material)?child.material:[child.material];materials.forEach(function(material){if(material.map)material.map.dispose();material.dispose();});}if(child.userData&&child.userData.labelTexture)child.userData.labelTexture.dispose();if(child.userData&&child.userData.ownedTexture)child.userData.ownedTexture.dispose();});}

    function renderBreadcrumbs(){var root=currentCodebase&&currentCodebase.nodes.find(function(node){return node.kind==='code_root';});var cluster=codeNode(focusClusterId);var symbol=codeNode(focusSymbolId)||(currentExpansion&&currentExpansion.nodes.find(function(node){return node.id===focusSymbolId;}));var parts=[root&&root.name,cluster&&cluster.name,symbol&&symbol.name].filter(Boolean);document.getElementById('breadcrumbs').innerHTML=parts.map(function(part,index){return (index?'<span class="separator">/</span>':'')+'<button class="crumb" data-level="'+index+'" '+(index===parts.length-1?'disabled':'')+'>'+escapeHtml(part)+'</button>';}).join('');document.getElementById('backLevel').disabled=currentLod===0;document.querySelectorAll('.crumb:not(:disabled)').forEach(function(button){button.addEventListener('click',function(){goToLevel(Number(button.dataset.level));});});}
    function escapeHtml(value){return String(value).replace(/[&<>"']/g,function(character){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character];});}
    function goToLevel(level){if(level<=0){currentLod=0;focusClusterId=null;focusSymbolId=null;currentExpansion=null;}else if(level===1){currentLod=1;focusSymbolId=null;currentExpansion=null;}rebuildGraph();}
    function backLevel(){goToLevel(Math.max(0,currentLod-1));}
    async function drillInto(node){if(node.sourceLayer!=='codebase')return;if(node.kind==='code_root'){goToLevel(0);return;}if(node.kind==='code_cluster'){focusClusterId=node.id;focusSymbolId=null;currentExpansion=null;currentLod=1;rebuildGraph();setStatus('Cluster opened. Pinch a purple symbol for its live one-hop call graph.');return;}if(node.kind==='code_symbol'&&node.lookupKey){await drillSymbol(node);}}
    async function drillSymbol(node){setStatus('Querying the live one-hop call graph…');var cacheKey=currentCodebase.project+'\n'+node.lookupKey;var expansion=expansionCache.get(cacheKey);if(!expansion){expansion=await api('/v1/inspector/codebase-spatial-expand',{project:currentCodebase.project,symbol:node.lookupKey});expansionCache.set(cacheKey,expansion);}currentExpansion=expansion;focusSymbolId=expansion.focusId;currentLod=2;rebuildGraph();setStatus('Local call graph loaded. Only this bounded neighborhood was queried.');}

    function controller(index){var item=renderer.xr.getController(index);item.userData.controllerIndex=index;item.addEventListener('selectstart',beginGesture);item.addEventListener('selectend',endGesture);item.addEventListener('select',selectFromController);var geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(0,0,-3)]);item.add(new THREE.Line(geometry,new THREE.LineBasicMaterial({color:index?0x36e6ff:0xa8ff4f,transparent:true,opacity:.72,blending:THREE.AdditiveBlending})));scene.add(item);controllers.push(item);}
    controller(0);controller(1);
    function beginGesture(){var index=this.userData.controllerIndex;gestures[index].active=true;gestures[index].startedAt=performance.now();if(gestures[0].active&&gestures[1].active){var a=worldPosition(controllers[0]),b=worldPosition(controllers[1]);dualGesture={distance:Math.max(.05,a.distanceTo(b)),angle:Math.atan2(b.z-a.z,b.x-a.x),scale:graphGroup.scale.x,rotation:graphGroup.rotation.y,mid:a.clone().add(b).multiplyScalar(.5),position:graphGroup.position.clone()};}}
    function endGesture(){gestures[this.userData.controllerIndex].active=false;if(dualGesture){dualGesture=null;gestureBlockedUntil=performance.now()+280;}}
    function worldPosition(object){var value=new THREE.Vector3();object.getWorldPosition(value);return value;}
    function updateGestures(){if(!dualGesture||!gestures[0].active||!gestures[1].active)return;var a=worldPosition(controllers[0]),b=worldPosition(controllers[1]);var distance=Math.max(.05,a.distanceTo(b));var angle=Math.atan2(b.z-a.z,b.x-a.x);var midpoint=a.clone().add(b).multiplyScalar(.5);var scale=Math.max(.45,Math.min(2.2,dualGesture.scale*(distance/dualGesture.distance)));graphGroup.scale.setScalar(scale);graphGroup.rotation.y=dualGesture.rotation-(angle-dualGesture.angle);graphGroup.position.copy(dualGesture.position).add(midpoint.sub(dualGesture.mid));}
    function controllerHit(item){rotationMatrix.identity().extractRotation(item.matrixWorld);raycaster.ray.origin.setFromMatrixPosition(item.matrixWorld);raycaster.ray.direction.set(0,0,-1).applyMatrix4(rotationMatrix);return raycaster.intersectObjects(nodeMeshes,true)[0];}
    function selectFromController(){if(dualGesture||(gestures[0].active&&gestures[1].active)||performance.now()<gestureBlockedUntil)return;var hit=controllerHit(this);if(hit)selectMesh(hit.object);}
    function graphMesh(object){var current=object;while(current&&!current.userData.graphNode)current=current.parent;return current&&current.userData.graphNode?current:null;}
    function selectMesh(mesh){mesh=graphMesh(mesh);if(!mesh)return;if(selectedMesh)setVisualScale(selectedMesh,1);selectedMesh=mesh;setVisualScale(selectedMesh,1.36);spawnShockwave(mesh);var world=new THREE.Vector3();mesh.getWorldPosition(world);selectionHalo.position.copy(world);selectionHalo.visible=true;var node=mesh.userData.graphNode;document.getElementById('detailName').textContent=node.name;document.getElementById('detailMeta').textContent=(node.detail?node.detail+' · ':'')+node.sourceLayer+' · '+node.kind+' · '+node.confirmationState;document.getElementById('detail').classList.add('show');window.setTimeout(function(){drillInto(node).catch(function(error){setStatus(error.message||String(error));});},140);}
    function spawnShockwave(mesh){var color=nodeColor(mesh.userData.graphNode);for(var i=0;i<(cinematic()?2:1);i++){var wave=glowSprite(color,.16,.75);wave.position.copy(mesh.position);wave.userData.waveAge=-i*.12;wave.userData.waveDuration=.78+i*.12;graphGroup.add(wave);shockwaves.push(wave);}}
    function setVisualScale(mesh,multiplier){mesh.userData.visualMultiplier=multiplier;}
    function setHover(next){next=graphMesh(next);if(next===hoverMesh)return;if(hoverMesh&&hoverMesh!==selectedMesh)setVisualScale(hoverMesh,1);hoverMesh=next;if(hoverMesh&&hoverMesh!==selectedMesh)setVisualScale(hoverMesh,1.16);}
    function updateHover(){if(!currentSession)return;var next=null;for(var i=0;i<controllers.length;i++){var hit=controllerHit(controllers[i]);if(hit){next=hit.object;break;}}setHover(next);}
    function pointerHit(event){var bounds=canvas.getBoundingClientRect();var point=new THREE.Vector2(((event.clientX-bounds.left)/bounds.width)*2-1,-((event.clientY-bounds.top)/bounds.height)*2+1);raycaster.setFromCamera(point,camera);return raycaster.intersectObjects(nodeMeshes,true)[0];}
    canvas.addEventListener('pointermove',function(event){if(currentSession)return;var hit=pointerHit(event);setHover(hit&&hit.object||null);canvas.style.cursor=hit?'pointer':'default';});
    canvas.addEventListener('pointerleave',function(){if(!currentSession)setHover(null);});
    canvas.addEventListener('pointerup',function(event){if(currentSession)return;var hit=pointerHit(event);if(hit)selectMesh(hit.object);});

    async function enterMixedReality(){try{if(!navigator.xr)throw new Error('WebXR is unavailable. Use Meta Quest Browser through the paired LAN connection.');if(!(await navigator.xr.isSessionSupported('immersive-ar')))throw new Error('This browser does not support immersive passthrough.');currentSession=await navigator.xr.requestSession('immersive-ar',{requiredFeatures:['local-floor'],optionalFeatures:['hand-tracking','dom-overlay'],domOverlay:{root:document.getElementById('overlay')}});await renderer.xr.setSession(currentSession);renderer.setClearColor(0x000000,0);atmosphere.visible=false;graphGroup.position.set(0,1.42,-2.05);graphGroup.rotation.set(0,0,0);graphGroup.scale.setScalar(.95);document.getElementById('enterMR').hidden=true;document.getElementById('exitMR').hidden=false;setStatus('Quest passthrough active. Pinch selects; two-hand pinch scales and rotates.');currentSession.addEventListener('end',function(){currentSession=null;renderer.setClearColor(0x020809,1);atmosphere.visible=true;graphGroup.position.set(0,0,0);graphGroup.rotation.set(0,0,0);graphGroup.scale.setScalar(1);document.getElementById('enterMR').hidden=false;document.getElementById('exitMR').hidden=true;setStatus('Mixed reality ended. Local 3D workbench remains active.');});}catch(error){setStatus(error.message||String(error));}}
    function updateInput(){if(!currentSession)return;currentSession.inputSources.forEach(function(source){var axes=source.gamepad&&source.gamepad.axes||[];var x=axes.length>=2?axes[axes.length-2]:0;var y=axes.length>=1?axes[axes.length-1]:0;if(Math.abs(x)>.15)graphGroup.rotation.y-=x*.025;if(Math.abs(y)>.15)graphGroup.position.y-=y*.008;});updateGestures();updateHover();}
    function animate(time){var delta=lastFrameTime?Math.min(.1,(time-lastFrameTime)/1000):0;lastFrameTime=time;if(!currentSession)graphGroup.rotation.y+=delta*.028;else updateInput();var revealElapsed=(time-graphRevealAt)/1000;graphGroup.children.forEach(function(child){if(child.userData.spin)child.rotation.y+=child.userData.spin*(currentSession?1:2);if(child.userData.pulseLine&&child.material)child.material.opacity=(child.userData.baseOpacity||.4)*(.82+Math.sin(time*.0018)*.18);if(child.userData.revealDelay!==undefined&&child.material)child.material.opacity=Math.min(1,Math.max(0,(revealElapsed-child.userData.revealDelay)/.32));if(child.userData.orbit){var orbit=child.userData.orbit;var phase=time*.001*orbit.speed+orbit.phase;child.position.set(orbit.center.x+Math.cos(phase)*orbit.radius,orbit.center.y+Math.sin(phase)*orbit.radius*.52,orbit.center.z+Math.sin(phase+orbit.tilt)*orbit.radius*.68);}});nodeMeshes.forEach(function(mesh){var t=Math.min(1,Math.max(0,(revealElapsed-mesh.userData.revealDelay)/.52));var eased=1-Math.pow(1-t,3);mesh.scale.setScalar(mesh.userData.baseScale*mesh.userData.visualMultiplier*eased);mesh.rotation.y+=delta*(mesh.userData.graphNode.kind==='code_root'?.55:.24);mesh.rotation.x+=delta*.08;if(mesh.material&&mesh.material.emissiveIntensity!==undefined)mesh.material.emissiveIntensity=(mesh.userData.graphNode.kind==='code_root'?.55:.34)+Math.sin(time*.0016+mesh.userData.pulse)*.1;});edgeFlows.forEach(function(particle){var flow=particle.userData.flow;flow.progress=(flow.progress+delta*flow.speed)%1;particle.position.copy(flow.curve.getPoint(flow.progress));var sparkle=.7+Math.sin(time*.006+flow.progress*12)*.3;particle.scale.setScalar(sparkle);});for(var waveIndex=shockwaves.length-1;waveIndex>=0;waveIndex--){var wave=shockwaves[waveIndex];wave.userData.waveAge+=delta;if(wave.userData.waveAge<0)continue;var progress=Math.min(1,wave.userData.waveAge/wave.userData.waveDuration);wave.scale.setScalar(.16+progress*.92);wave.material.opacity=(1-progress)*.72;if(progress>=1){graphGroup.remove(wave);disposeObject(wave);shockwaves.splice(waveIndex,1);}}atmosphere.rotation.y+=delta*.008;if(selectionHalo.visible&&selectedMesh){selectedMesh.getWorldPosition(selectionHalo.position);selectionHalo.quaternion.copy(camera.quaternion);selectionHalo.rotation.z+=delta*1.15;}renderer.render(scene,camera);perfFrames++;if(!perfWindowStart)perfWindowStart=time;if(time-perfWindowStart>=1000){var badge=document.getElementById('perfBadge');if(badge)badge.textContent=Math.round(perfFrames*1000/(time-perfWindowStart))+' fps · '+renderer.info.render.calls+' draws';perfFrames=0;perfWindowStart=time;}}
    renderer.setAnimationLoop(animate);

    document.getElementById('overlay').addEventListener('beforexrselect',function(event){event.preventDefault();});document.getElementById('enterMR').addEventListener('click',enterMixedReality);document.getElementById('exitMR').addEventListener('click',function(){if(currentSession)currentSession.end();});document.getElementById('backLevel').addEventListener('click',backLevel);document.getElementById('refresh').addEventListener('click',function(){var project=document.getElementById('project').value;loadProject(project).catch(function(error){setStatus(error.message||String(error));});});document.getElementById('project').addEventListener('change',function(event){loadProject(event.target.value).catch(function(error){setStatus(error.message||String(error));});});document.getElementById('layer').addEventListener('change',rebuildGraph);document.getElementById('effects').addEventListener('change',function(){scene.remove(atmosphere);disposeObject(atmosphere);atmosphere=createAtmosphere();atmosphere.visible=!currentSession;scene.add(atmosphere);rebuildGraph();});window.addEventListener('resize',function(){camera.aspect=window.innerWidth/window.innerHeight;camera.updateProjectionMatrix();renderer.setSize(window.innerWidth,window.innerHeight);});authenticate().catch(function(error){setStatus('Open Boron Spatial from the authenticated Inspector or run boron-context quest-inspector. '+(error.message||String(error)));});
  </script>
</body>
</html>`
}
